#spring.application.name=Hotel_App
server:
  port: 8080
  servlet:
    context-path: /hotel_app
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/hotel_app"
    username: root
    password: Dung2002.
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true